import { ACHIEVEMENT_COLLECTION, CONTACT_COLLECTION, EDUCATION_COLLECTION, EXPERIENCE_COLLECTION, PROJECT_COLLECTION, SKILL_COLLECTION, SOCIAL_COLLECTION, TECHNOLOGY_COLLECTION } from "./dbconstants";

export enum AVAILABLE_SUBSECTIONS {
  EXPERIENCE = EXPERIENCE_COLLECTION,
  PROJECT = PROJECT_COLLECTION,
  EDUCATION = EDUCATION_COLLECTION,
  SKILL = SKILL_COLLECTION,
  TECHNOLOGY = TECHNOLOGY_COLLECTION,
  ACHIEVEMENT = ACHIEVEMENT_COLLECTION,
  CONTACT = CONTACT_COLLECTION,
  SOCIAL = SOCIAL_COLLECTION,
}
