"use client";

export const EXPERIENCE_SUBSECTION = "experience";
export const PROJECT_SUBSECTION = "project";
export const EDUCATION_SUBSECTION = "education";
export const SKILL_SUBSECTION = "skill";
export const TECHNOLOGY_SUBSECTION = "technology";
export const ACHIEVEMENT_SUBSECTION = "achievement";
export const CONTACT_SUBSECTION = "links";
export const SOCIAL_SUBSECTION = "social";
export const ABOUT_SUBSECTION = "about";

export enum AVAILABLE_SUBSECTIONS {
  EXPERIENCE = EXPERIENCE_SUBSECTION,
  PROJECT = PROJECT_SUBSECTION,
  EDUCATION = EDUCATION_SUBSECTION,
  SKILL = SKILL_SUBSECTION,
  TECHNOLOGY = TECHNOLOGY_SUBSECTION,
  ACHIEVEMENT = ACHIEVEMENT_SUBSECTION,
  CONTACT = CONTACT_SUBSECTION,
  SOCIAL = SOCIAL_SUBSECTION,
  ABOUT = ABOUT_SUBSECTION,
}

export const TABULATED_COLLECTIONS = [
  AVAILABLE_SUBSECTIONS.EXPERIENCE,
  AVAILABLE_SUBSECTIONS.PROJECT,
  AVAILABLE_SUBSECTIONS.EDUCATION,
  AVAILABLE_SUBSECTIONS.SKILL,
  AVAILABLE_SUBSECTIONS.TECHNOLOGY,
  AVAILABLE_SUBSECTIONS.ACHIEVEMENT,
  AVAILABLE_SUBSECTIONS.SOCIAL,
];