export const EXPERIENCE_SUBSECTION = "experience";
export const PROJECT_SUBSECTION = "project";
export const EDUCATION_SUBSECTION = "education";
export const SKILL_SUBSECTION = "skill";
export const ACHIEVEMENT_SUBSECTION = "achievement";
export const BLOG_SUBSECTION = "blog";

export enum AVAILABLE_SUBSECTIONS {
  EXPERIENCE = EXPERIENCE_SUBSECTION,
  PROJECT = PROJECT_SUBSECTION,
  EDUCATION = EDUCATION_SUBSECTION,
  SKILL = SKILL_SUBSECTION,
  ACHIEVEMENT = ACHIEVEMENT_SUBSECTION,
  BLOG = BLOG_SUBSECTION,
}