import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import StaticNavbar from "@/components/staticNavbar";
import getContact from "@/services/dataService";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const contactDetail = await getContact();

  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <StaticNavbar contactDetail={contactDetail} />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
