import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import StaticNavbar from "@/components/staticNavbar";
import { Fab } from "@/components/fab";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <StaticNavbar />
            {children}
            <Fab />
          </div>
        </Providers>
      </body>
    </html>
  );
}
